SistemaCadastro/SistemaCadastro/Models/ContatoModel.cs
namespace SistemaCadastro.Models
{
    public class ContatoModel
    {
        public int Id {  get; set; }
        public string Name { get; set; }    
        public string Email{ get; set; }
        public string Phone { get; set; }
    }
}

SistemaCadastro/SistemaCadastro/Models/ErrorViewModel.cs
namespace SistemaCadastro.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SistemaCadastro/SistemaCadastro/Controllers/ContactosController.cs
using Microsoft.AspNetCore.Mvc;



namespace SistemaCadastro.Controllers;

public class ContactosController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
    
    public IActionResult Adicionar()
    {
        return View();
    }
    
    public IActionResult Apagar()
    {
        return View();
    }
    
    public IActionResult Editar()
    {
        return View();
    }
    
    
}

SistemaCadastro/SistemaCadastro/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SistemaCadastro.Models;

namespace SistemaCadastro.Controllers;

public class HomeController : Controller
{
    

    public IActionResult Index()
    {
        return View();
    }

   

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SistemaCadastro/SistemaCadastro/Views/Contactos/Adicionar.cshtml
@model SistemaCadastro.Controllers.ContactosController

@{
    ViewData["Title"] = "Adicionar";
}

<div class="text-center">
    
<h1> Adicionar Registo</h1>
    
</div>

<form>
    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="Text" class="form-control" >
       
    </div>
    <div class="mb-3">
        <label class="form-label">Email </label>
        <input type="Text" class="form-control" >
        
    </div>
    
    <div class="mb-3">
        <label class="form-label">Contacto</label>
        <input type="Text" class="form-control" >
        
    </div>
    
    
    
    <button type="submit" class="btn btn-primary">Submit</button>
    <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Index">Cancelar</a>
</form>

SistemaCadastro/SistemaCadastro/Views/Contactos/Apagar.cshtml
@model SistemaCadastro.Controllers.ContactosController

@{
    ViewData["Title"] = "Confirmacao";
}

<h1>Deseja mesmo apagar o registo?</h1>
<button type="button" class="btn btn-primary">Apagar</button>
<a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Index">Cancelar</a>

SistemaCadastro/SistemaCadastro/Views/Contactos/Editar.cshtml
@model SistemaCadastro.Controllers.ContactosController

@{
    ViewData["Title"] = "Editar";
}

<div class="text-center">
    
    <h1> Editar Registo</h1>
    
</div>

<form>
    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="Text" class="form-control" >
       
    </div>
    <div class="mb-3">
        <label class="form-label">Email </label>
        <input type="Text" class="form-control" >
        
    </div>
    
    <div class="mb-3">
        <label class="form-label">Contacto</label>
        <input type="Text" class="form-control" >
        
    </div>
    
    
    
    <button type="submit" class="btn btn-primary">Submit</button>
    <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Index">Cancelar</a>
</form>

SistemaCadastro/SistemaCadastro/Views/Contactos/Index.cshtml
@model SistemaCadastro.Controllers.ContactosController

@{
    ViewData["Title"] = "DataBase";
}

<div class="align-content-lg-end">
    <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Adicionar">Adicionar Contacto</a>
</div>

<div class="text-center">
    <h1 class="display-4">Resgisto de contactos</h1>
</div>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Numero Contacto</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto@gmail.com</td>
        <td>123456789</td>
        <td>
            <div class="btn-group" role="group" >
                <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Editar">Editar</a>
                <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Apagar" >Apagar</a>
            </div>
        </td>
    </tr>
    
    <tr>
        <th scope="row">2</th>
        <td>Mark</td>
        <td>Otto@gmail.com</td>
        <td>123456789</td>
        <td>
            <div class="btn-group" role="group" >
                <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Editar">Editar</a>
                <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Apagar" >Apagar</a>
            </div>
        </td>
    </tr>
    
    <tr>
        <th scope="row">3</th>
        <td>Mark</td>
        <td>Otto@gmail.com</td>
        <td>123456789</td>
        <td>
            <div class="btn-group" role="group" >
                <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Editar">Editar</a>
                <a role="button" class="btn btn-primary" asp-controller="Contactos" asp-action="Apagar">Apagar</a>
            </div>
        </td>
    </tr>
    
  
    </tbody>
</table>

SistemaCadastro/SistemaCadastro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Principal";
}
<div class="text-center">
        
    <h1 class="display-4">Sistema CRUD</h1>
    <p>Aplicacao de registo de contactos numa Database em asp.net core mvc</p>
    
</div>

SistemaCadastro/SistemaCadastro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Sistema CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SistemaCadastro.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema CRUD</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Contactos" asp-action="Index">Database</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Sistema CRUD - Vitor Ribeiro 78138 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>